smtp_on: true
smtp_host: 172.32.0.173
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_autotls: false
smtp_timeout: 60
smtp_username: ''
smtp_password: ''
smtp_from: swarajsupport@emailmahindra.com
smtp_fromname: 'Swaraj Tractors'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
